name: Deploy to Development

on:
  workflow_dispatch:

jobs:
  deploy-development:
    name: Deploy development
    uses: VMVT-DevHub/reusable-workflows/.github/workflows/g9-deploy.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: Development
      docker-image: ghcr.io/VMVT-DevHub/g9-app
      build-args: |
        NODE_ENV=development